apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crusoe-npd.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crusoe-npd.labels" . | nindent 4 }}
data:
  {{- range .Values.monitors }}
  {{ .name }}-monitor.json: |
    {
        "plugin": "custom",
        "pluginConfig": {
            "invoke_interval": {{ (.invokeInterval | default $.Values.pluginDefaults.invokeInterval) | quote }},
            "timeout": {{ (.timeout | default $.Values.pluginDefaults.timeout) | quote }},
            "max_output_length": {{ .maxOutputLength | default $.Values.pluginDefaults.maxOutputLength }},
            "concurrency": {{ .concurrency | default $.Values.pluginDefaults.concurrency }},
            "skip_initial_status": {{ .skipInitialStatus | default $.Values.pluginDefaults.skipInitialStatus }}
        },
        "source": "gpu-health-monitor",
        "conditions": [
            {
                "type": {{ .conditionType | quote }},
                "reason": {{ .conditionReason | quote }},
                "message": {{ .conditionMessage | quote }}
            }
        ],
        "rules": [
            {
                "type": "permanent",
                "condition": {{ .conditionType | quote }},
                "reason": {{ .failedReason | quote }},
                "path": "/config/plugin/check_gpu_health.sh",
                "args": [{{ .name | quote }}, {{ .conditionType | quote }}]
            }
        ]
    }
  {{- end }}
