apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crusoe-npd.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crusoe-npd.labels" . | nindent 4 }}
